### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by thezaeemaanwar**

### CODE REVIEW

**Comment by thezaeemaanwar** [comment]
Kindly label it as hacktoberfest-accepted so it may count in hacktober fest

**Comment by Potential17** [comment]
"hacktoberfest" topic  has already added to the repo!

**Comment by thezaeemaanwar** [comment]
Yep but I still got a invalid repo label on my hacktoberfest profile 

Zaeema Anwar

**Comment by Potential17** [comment]
Kindly contact me here - https://t.me/imdev17

**Comment by thezaeemaanwar** [comment]
Somehow it is solved.
BTW Thanks for corporation :)

**Pull request merged**
