### PR TITLE
added search bar with autocomplete feature 

### LINKED ISSUE #88: Add SearchBar
A search bar with auto complete options and quickly displays the matching result of Hactoberfest participants listed on the site.

### PR DESCRIPTION
**Pull request by udayax**
added search bar with autocomplete feature and made display participate list responsive using flex . waiting for your kind reply

### CODE REVIEW

**Comment by Potential17** [comment]
Your work is really impressive,
Keep contributing!

**Comment by udayax** [comment]
thank you  .. 
looking forward at you for any further contribution .
Your GitHub profile is impressive.
contact me if you need any help .
I am currently working with React .

**Comment by Potential17** [comment]
Sure,
You can ping me here - 
shashwat171@outlook.com

**Comment by udayax** [comment]
Sure 😃

**Pull request merged**
